/**
 * Message audit logger.
 *
 * Every message the middleware receives from (or sends to) a lab analyzer
 * gets recorded here. Think of it as a flight recorder for lab data —
 * if something goes wrong, we can look back and see exactly what happened.
 *
 * Uses SQLite (better-sqlite3) so it works even when the internet is down.
 * In tests, pass ':memory:' as the dbPath to avoid writing to disk.
 */

import Database from 'better-sqlite3';
import type { MessageLogEntry } from '../types/result.js';
import { encrypt, decryptOrPassthrough } from '../crypto/fieldEncryption.js';

/** Fields required when logging a new message (id is auto-generated by SQLite) */
export type NewMessageLogEntry = Omit<MessageLogEntry, 'id'>;

/** Filters for querying message logs */
export interface MessageQueryFilters {
  analyzerId?: string;
  status?: string;
  from?: string; // ISO date string
  to?: string; // ISO date string
  limit?: number; // default 50
  offset?: number; // default 0
}

export class MessageLogger {
  private db: Database.Database;
  private encryptionKey?: string;

  constructor(dbPath: string, encryptionKey?: string) {
    this.db = new Database(dbPath);
    this.encryptionKey = encryptionKey;
    this.db.pragma('journal_mode = WAL');
    this.createTable();
  }

  /** Creates the message_log table and indexes if they don't exist */
  private createTable(): void {
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS message_log (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        timestamp TEXT NOT NULL DEFAULT (datetime('now')),
        analyzer_id TEXT NOT NULL,
        analyzer_name TEXT NOT NULL,
        direction TEXT NOT NULL,
        protocol TEXT NOT NULL,
        raw_content TEXT NOT NULL,
        parsed_summary TEXT,
        fhir_resource_ids TEXT DEFAULT '[]',
        status TEXT NOT NULL,
        error_message TEXT
      );

      CREATE INDEX IF NOT EXISTS idx_message_log_timestamp ON message_log(timestamp);
      CREATE INDEX IF NOT EXISTS idx_message_log_analyzer ON message_log(analyzer_id);
      CREATE INDEX IF NOT EXISTS idx_message_log_status ON message_log(status);
    `);
  }

  /** Logs a message and returns the new entry's ID */
  logMessage(entry: NewMessageLogEntry): number {
    const stmt = this.db.prepare(`
      INSERT INTO message_log (timestamp, analyzer_id, analyzer_name, direction, protocol, raw_content, parsed_summary, fhir_resource_ids, status, error_message)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `);

    const rawContent = this.encryptionKey
      ? encrypt(entry.rawContent, this.encryptionKey)
      : entry.rawContent;

    const result = stmt.run(
      entry.timestamp,
      entry.analyzerId,
      entry.analyzerName,
      entry.direction,
      entry.protocol,
      rawContent,
      entry.parsedSummary,
      JSON.stringify(entry.fhirResourceIds),
      entry.status,
      entry.errorMessage ?? null
    );

    return Number(result.lastInsertRowid);
  }

  /** Queries messages with optional filters and pagination */
  queryMessages(filters: MessageQueryFilters = {}): MessageLogEntry[] {
    const { where, params } = this.buildWhereClause(filters);
    const limit = filters.limit ?? 50;
    const offset = filters.offset ?? 0;

    const stmt = this.db.prepare(
      `SELECT * FROM message_log ${where} ORDER BY id DESC LIMIT ? OFFSET ?`
    );

    const rows = stmt.all(...params, limit, offset) as RawRow[];
    return rows.map((row) => rowToEntry(row, this.encryptionKey));
  }

  /** Gets a single message by ID, or null if not found */
  getMessageById(id: number): MessageLogEntry | null {
    const stmt = this.db.prepare('SELECT * FROM message_log WHERE id = ?');
    const row = stmt.get(id) as RawRow | undefined;
    return row ? rowToEntry(row, this.encryptionKey) : null;
  }

  /** Returns the count of messages matching the given filters */
  getCount(filters: Pick<MessageQueryFilters, 'analyzerId' | 'status'> = {}): number {
    const { where, params } = this.buildWhereClause(filters);
    const stmt = this.db.prepare(`SELECT COUNT(*) as count FROM message_log ${where}`);
    const row = stmt.get(...params) as { count: number };
    return row.count;
  }

  /** Deletes messages older than the specified number of days. Returns count deleted. */
  pruneOldMessages(olderThanDays: number): number {
    const result = this.db.prepare(
      "DELETE FROM message_log WHERE timestamp < datetime('now', ? || ' days')"
    ).run(`-${olderThanDays}`);
    return result.changes;
  }

  /** Returns the raw SQLite database instance (for testing/inspection only). */
  getRawDb(): Database.Database {
    return this.db;
  }

  /** Closes the SQLite database connection */
  close(): void {
    this.db.close();
  }

  /** Builds a WHERE clause from the filters */
  private buildWhereClause(filters: MessageQueryFilters): { where: string; params: unknown[] } {
    const conditions: string[] = [];
    const params: unknown[] = [];

    if (filters.analyzerId) {
      conditions.push('analyzer_id = ?');
      params.push(filters.analyzerId);
    }
    if (filters.status) {
      conditions.push('status = ?');
      params.push(filters.status);
    }
    if (filters.from) {
      conditions.push('timestamp >= ?');
      params.push(filters.from);
    }
    if (filters.to) {
      conditions.push('timestamp <= ?');
      params.push(filters.to);
    }

    const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';
    return { where, params };
  }
}

// ---------------------------------------------------------------------------
// Internal helpers — convert SQLite rows (snake_case) to TypeScript (camelCase)
// ---------------------------------------------------------------------------

/** Raw row shape from SQLite */
interface RawRow {
  id: number;
  timestamp: string;
  analyzer_id: string;
  analyzer_name: string;
  direction: string;
  protocol: string;
  raw_content: string;
  parsed_summary: string | null;
  fhir_resource_ids: string;
  status: string;
  error_message: string | null;
}

/** Converts a raw SQLite row to a MessageLogEntry, optionally decrypting rawContent */
function rowToEntry(row: RawRow, encryptionKey?: string): MessageLogEntry {
  const rawContent = encryptionKey
    ? decryptOrPassthrough(row.raw_content, encryptionKey)
    : row.raw_content;

  return {
    id: row.id,
    timestamp: row.timestamp,
    analyzerId: row.analyzer_id,
    analyzerName: row.analyzer_name,
    direction: row.direction as 'inbound' | 'outbound',
    protocol: row.protocol,
    rawContent,
    parsedSummary: row.parsed_summary ?? '',
    fhirResourceIds: JSON.parse(row.fhir_resource_ids) as string[],
    status: row.status as MessageLogEntry['status'],
    errorMessage: row.error_message ?? undefined,
  };
}
